server:
  port: 7070
  servlet:
    contextPath: /api
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/shopping
    username: shopping
    password: helloshopping
  queries:
    users-query: select email, password, active from users where email=?
    roles-query: select email, role from users where email=?
logging:
  path: logs/shopping/
  level:
    wiki:
      pde: debug
    root: info
    org:
      apache:
        catalina: error
      springframework:
        root: error
        jdbc:
          core:
            JdbcTemplate: debug
            StatementCreatorUtils: trace
jwtSecret: me.zhulin
jwtExpiration: 86400